name: Build and Deploy
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: true

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gnupg
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Build and Deploy with Maven
        run: mvn --batch-mode clean deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GPG_PASS: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          REPSY_PASS: ${{ secrets.REPSY_PASS }}